name: Build and Upload Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          submodules: false # Don't fetch submodules

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bats partclone util-linux gawk coreutils parted e2fsprogs xz-utils
          python -m pip install --upgrade pip

      - name: Install Bats test helpers
        run: |
          # Create test helper directory
          mkdir -p tests/test_helper
          # Clone test helpers directly
          git clone https://github.com/bats-core/bats-support.git tests/test_helper/bats-support
          git clone https://github.com/bats-core/bats-assert.git tests/test_helper/bats-assert
          git clone https://github.com/bats-core/bats-file.git tests/test_helper/bats-file
          # Remove .git directories to prevent submodule issues
          rm -rf tests/test_helper/*/.git

      - name: Prepare test environment
        run: |
          # Create the installer directory in tests if it doesn't exist
          mkdir -p tests/installer
          # Copy sc.sh to the expected location
          cp installer/sc.sh tests/installer/
          # Make it executable
          chmod +x tests/installer/sc.sh

      - name: Run Bats tests
        run: |
          cd tests
          ./run_bats_tests.sh

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          submodules: false # Don't fetch submodules

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        working-directory: ./installer
        run: |
          python -m pip install --upgrade pip

      - name: Run build script
        working-directory: ./installer
        run: |
          python3 build.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        working-directory: ./installer
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 cp skycore.tar.gz s3://$S3_BUCKET_NAME/skycore.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: skycore.tar.gz
          path: ./installer/skycore.tar.gz
