name: Build and Upload Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        working-directory: ./installer
        run: |
          python -m pip install --upgrade pip

      - name: Run build script
        working-directory: ./installer
        run: |
          python3 build.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        working-directory: ./installer
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 cp skycore.tar.gz s3://$S3_BUCKET_NAME/skycore.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: skycore.tar.gz
          path: ./installer/skycore.tar.gz
